new Vue({
    el: "#add-font-template",
    data: {
        fonts: [
            { 'name': 'Aclonica'},
            { 'name': 'Allan'},
            { 'name': 'Annie Use Your Telescope'},
            { 'name': 'Anonymous Pro'},
            { 'name': 'Allerta Stencil'},
            { 'name': 'Allerta'},
            { 'name': 'Amaranth'},
            { 'name': 'Anton'},
            { 'name': 'Architects Daughter'},
            { 'name': 'Arimo'},
            { 'name': 'Artifika'},
            { 'name': 'Arvo'},
            { 'name': 'Asset'},
            { 'name': 'Astloch'},
            { 'name': 'Bangers'},
            { 'name': 'Bentham'},
            { 'name': 'Bevan'},
            { 'name': 'Bigshot One'},
            { 'name': 'Bowlby One'},
            { 'name': 'Bowlby One SC'},
            { 'name': 'Brawler'},
            { 'name': 'Buda:300'},
            { 'name': 'Cabin'},
            { 'name': 'Calligraffitti'},
            { 'name': 'Candal'},
            { 'name': 'Cantarell'},
            { 'name': 'Cardo'},
            { 'name': 'Carter One'},
            { 'name': 'Caudex'},
            { 'name': 'Cedarville Cursive'},
            { 'name': 'Cherry Cream Soda'},
            { 'name': 'Chewy'},
            { 'name': 'Coda'},
            { 'name': 'Coming Soon'},
            { 'name': 'Copse'},
            { 'name': 'Corben:700'},
            { 'name': 'Cousine'},
            { 'name': 'Covered By Your Grace'},
            { 'name': 'Crafty Girls'},
            { 'name': 'Crimson Text'},
            { 'name': 'Crushed'},
            { 'name': 'Cuprum'},
            { 'name': 'Damion'},
            { 'name': 'Dancing Script'},
            { 'name': 'Dawning of a New Day'},
            { 'name': 'Didact Gothic'},
            { 'name': 'Droid Sans'},
            { 'name': 'Droid Sans Mono'},
            { 'name': 'Droid Serif'},
            { 'name': 'EB Garamond'},
            { 'name': 'Expletus Sans'},
            { 'name': 'Fontdiner Swanky'},
            { 'name': 'Forum'},
            { 'name': 'Francois One'},
            { 'name': 'Geo'},
            { 'name': 'Give You Glory'},
            { 'name': 'Goblin One'},
            { 'name': 'Goudy Bookletter 1911'},
            { 'name': 'Gravitas One'},
            { 'name': 'Gruppo'},
            { 'name': 'Hammersmith One'},
            { 'name': 'Holtwood One SC'},
            { 'name': 'Homemade Apple'},
            { 'name': 'Inconsolata'},
            { 'name': 'Indie Flower'},
            { 'name': 'IM Fell DW Pica'},
            { 'name': 'IM Fell DW Pica SC'},
            { 'name': 'IM Fell Double Pica'},
            { 'name': 'IM Fell Double Pica SC'},
            { 'name': 'IM Fell English'},
            { 'name': 'IM Fell English SC'},
            { 'name': 'IM Fell French Canon'},
            { 'name': 'IM Fell French Canon SC'},
            { 'name': 'IM Fell Great Primer'},
            { 'name': 'IM Fell Great Primer SC'},
            { 'name': 'Irish Grover'},
            { 'name': 'Irish Growler'},
            { 'name': 'Istok Web'},
            { 'name': 'Josefin Sans'},
            { 'name': 'Josefin Slab'},
            { 'name': 'Judson'},
            { 'name': 'Jura'},
            { 'name': 'Jura:500'},
            { 'name': 'Jura:600'},
            { 'name': 'Just Another Hand'},
            { 'name': 'Just Me Again Down Here'},
            { 'name': 'Kameron'},
            { 'name': 'Kenia'},
            { 'name': 'Kranky'},
            { 'name': 'Kreon'},
            { 'name': 'Kristi'},
            { 'name': 'La Belle Aurore'},
            { 'name': 'Lato:100'},
            { 'name': 'Lato:100italic'},
            { 'name': 'Lato:300'},
            { 'name': 'Lato'},
            { 'name': 'Lato:bold'},
            { 'name': 'Lato:900'},
            { 'name': 'League Script'},
            { 'name': 'Lekton'},
            { 'name': 'Limelight'},
            { 'name': 'Lobster'},
            { 'name': 'Lobster Two'},
            { 'name': 'Lora'},
            { 'name': 'Love Ya Like A Sister'},
            { 'name': 'Loved by the King'},
            { 'name': 'Luckiest Guy'},
            { 'name': 'Maiden Orange'},
            { 'name': 'Mako'},
            { 'name': 'Maven Pro'},
            { 'name': 'Maven Pro:500'},
            { 'name': 'Maven Pro:700'},
            { 'name': 'Maven Pro:900'},
            { 'name': 'Meddon'},
            { 'name': 'MedievalSharp'},
            { 'name': 'Megrim'},
            { 'name': 'Merriweather'},
            { 'name': 'Metrophobic'},
            { 'name': 'Michroma'},
            { 'name': 'Miltonian Tattoo'},
            { 'name': 'Miltonian'},
            { 'name': 'Modern Antiqua'},
            { 'name': 'Monofett'},
            { 'name': 'Molengo'},
            { 'name': 'Mountains of Christmas'},
            { 'name': 'Muli:300'},
            { 'name': 'Muli'},
            { 'name': 'Neucha'},
            { 'name': 'Neuton'},
            { 'name': 'News Cycle'},
            { 'name': 'Nixie One'},
            { 'name': 'Nobile'},
            { 'name': 'Nova Cut'},
            { 'name': 'Nova Flat'},
            { 'name': 'Nova Mono'},
            { 'name': 'Nova Oval'},
            { 'name': 'Nova Round'},
            { 'name': 'Nova Script'},
            { 'name': 'Nova Slim'},
            { 'name': 'Nova Square'},
            { 'name': 'Nunito:light'},
            { 'name': 'Nunito'},
            { 'name': 'OFL Sorts Mill Goudy TT'},
            { 'name': 'Old Standard TT'},
            { 'name': 'Open Sans:300'},
            { 'name': 'Open Sans'},
            { 'name': 'Open Sans:600'},
            { 'name': 'Open Sans:800'},
            { 'name': 'Open Sans Condensed:300'},
            { 'name': 'Orbitron'},
            { 'name': 'Orbitron:500'},
            { 'name': 'Orbitron:700'},
            { 'name': 'Orbitron:900'},
            { 'name': 'Oswald'},
            { 'name': 'Over the Rainbow'},
            { 'name': 'Reenie Beanie'},
            { 'name': 'Pacifico'},
            { 'name': 'Patrick Hand'},
            { 'name': 'Paytone One'},
            { 'name': 'Permanent Marker'},
            { 'name': 'Philosopher'},
            { 'name': 'Play'},
            { 'name': 'Playfair Display'},
            { 'name': 'Podkova'},
            { 'name': 'PT Sans'},
            { 'name': 'PT Sans Narrow'},
            { 'name': 'PT Sans Narrow:regular,bold'},
            { 'name': 'PT Serif'},
            { 'name': 'PT Serif Caption'},
            { 'name': 'Puritan'},
            { 'name': 'Quattrocento'},
            { 'name': 'Quattrocento Sans'},
            { 'name': 'Radley'},
            { 'name': 'Raleway:100'},
            { 'name': 'Redressed'},
            { 'name': 'Rock Salt'},
            { 'name': 'Rokkitt'},
            { 'name': 'Roboto'},
            { 'name': 'Ruslan Display'},
            { 'name': 'Schoolbell'},
            { 'name': 'Shadows Into Light'},
            { 'name': 'Shanti'},
            { 'name': 'Sigmar One'},
            { 'name': 'Six Caps'},
            { 'name': 'Slackey'},
            { 'name': 'Smythe'},
            { 'name': 'Sniglet:800'},
            { 'name': 'Special Elite'},
            { 'name': 'Stardos Stencil'},
            { 'name': 'Sue Ellen Francisco'},
            { 'name': 'Sunshiney'},
            { 'name': 'Swanky and Moo Moo'},
            { 'name': 'Syncopate'},
            { 'name': 'Tangerine'},
            { 'name': 'Tenor Sans'},
            { 'name': 'Terminal Dosis Light'},
            { 'name': 'The Girl Next Door'},
            { 'name': 'Tinos'},
            { 'name': 'Ubuntu'},
            { 'name': 'Ultra'},
            { 'name': 'Unkempt'},
            { 'name': 'UnifrakturCook:bold'},
            { 'name': 'UnifrakturMaguntia'},
            { 'name': 'Varela'},
            { 'name': 'Varela Round'},
            { 'name': 'Vibur'},
            { 'name': 'Vollkorn'},
            { 'name': 'VT323'},
            { 'name': 'Waiting for the Sunrise'},
            { 'name': 'Wallpoet'},
            { 'name': 'Walter Turncoat'},
            { 'name': 'Wire One'},
            { 'name': 'Yanone Kaffeesatz'},
            { 'name': 'Yanone Kaffeesatz:300'},
            { 'name': 'Yanone Kaffeesatz:400'},
            { 'name': 'Yanone Kaffeesatz:700'},
            { 'name': 'Yeseva One'},
            { 'name': 'Zeyad'}
        ],
        selected_font: 'Arial'
    }
});